ref_vel_configulator:
  s1:
    ref_vel: 40.0
    wp_id: 0
  s1_1:
    ref_vel: 40.0
    wp_id: 11
  s2:
    ref_vel: 40.0
    wp_id: 52
  s3:
    ref_vel: 40.0
    wp_id: 81
  s4:
    ref_vel: 40.0
    wp_id: 136
    
  s5:
    ref_vel: 40.0
    wp_id: 171
  s6:
    ref_vel: 40.0
    wp_id: 246
  s7:
    ref_vel: 40.0
    wp_id: 271
  s8:
    ref_vel: 40.0
    wp_id: 301
  s9:
    ref_vel: 40.0
    wp_id: 311

