x-gpu: &gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: ["gpu"]

services:
  autoware:
    <<: *gpu

  simulator:
    <<: *gpu
